server:
  port: 8001

spring:
   application:
     name: cloud-payment-service
   datasource:
     # 当前数据源操作类型
     type: com.alibaba.druid.pool.DruidDataSource
     # mysql驱动类
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://115.29.142.129:3306/db2019?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
     username: root
     password: 123456
     # zipkin/sleuth链路跟踪
   zipkin:
      base-url: http://localhost:9411
   sleuth:
      sampler:
         # 采样值介于0到1之间,1表示全部采集
         probability: 1

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities

eureka:
  client:
    # 表示是否将自己注册进EurekaServer 默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true 单节点无所谓，集群必须设置true 才能配置ribbon使用负载均衡
    fetch-registry: true
    service-url:
#       defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

  instance:
    instance-id: payment8001
    # 访问路径可以显示ip地址
    prefer-ip-address: true

#####################################Eureka客户端自我保护配置
    # Eureka客户端向服务端发送心跳的时间间隔,单位为秒(默认是30秒)
    lease-renewal-interval-in-seconds: 1
    # Eureka服务端在收到最后一次心跳后等待时间上限 ,单位为秒(默认是90秒),超时剔除服务
    lease-expiration-duration-in-seconds: 2
#############################################################