server:
  port: 7001

spring:
  application:
    name: cloud-eureka-service

eureka:
  instance:
    hostname: eureka7001.com # eureka服务端示列名称
##########################################################eureka 自我保护机制服务端配置
  server:
    #禁用自我保护,保证不可用服务被及时删除
    enable-self-preservation: false
    #清理无效节点的时间间隔,默认60000毫秒,即60秒 (此处时间间隔设置为2s)
    eviction-interval-timer-in-ms: 2000
#############################################################

  client:
    #false 表示不向注册中心注册自己
    register-with-eureka: false
    #false 表示自己就是注册中心 我的职责就是维护服务实例 并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
#     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7002.com:7002/eureka
